# Generated by Django 3.0.4 on 2020-03-25 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dependencias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_de_expediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipos_de_expediente_detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('dependencia_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dependencias.Dependencia')),
                ('tipo_de_expediente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipos_de_expedientes.Tipo_de_expediente')),
            ],
        ),
    ]
